import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "Latihan next",
  description: "Generated by create next app",
  keywords: "Web Development, React, Next, Javascript"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <Header />
        <main className="px-6 py-6 container w-full md:w-[80%] lg:w-[65%] mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
